backend:
  name: github
  repo: robbie-likescodes/Tessa-Bennion-s-Art-Page
  branch: main
  # No OAuth proxy needed if the repo is PUBLIC (Decap uses GitHub's implicit auth flow)

media_folder: "uploads"
public_folder: "uploads"

publish_mode: editorial_workflow

collections:
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    slug: "{{year}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - label: "Gallery"
        name: "images"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
